// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzseqdjipvebudqomuco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6c2VxZGppcHZlYnVkcW9tdWNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTY5ODgsImV4cCI6MjA2NTQ5Mjk4OH0.wsZOB3bJXLFbh7Z8rBp3H9wWV_ekpkXvGSVos2DL6q4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);